//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Aliencube.Utilities.KoreanPostcodeAddressConverter.Services {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aliencube.org/schemas/2013/05/street-based-address")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://aliencube.org/schemas/2013/05/street-based-address", IsNullable=false)]
    public partial class StreetBasedAddresses {
        
        private StreetBasedAddress[] streetBasedAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StreetBasedAddress")]
        public StreetBasedAddress[] StreetBasedAddress {
            get {
                return this.streetBasedAddressField;
            }
            set {
                this.streetBasedAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://aliencube.org/schemas/2013/05/street-based-address")]
    public partial class StreetBasedAddress {
        
        private string postcodeField;
        
        private string sequenceNumberField;
        
        private string provinceField;
        
        private string provinceEngField;
        
        private string countyField;
        
        private string countyEngField;
        
        private string suburbField;
        
        private string suburbEngField;
        
        private string streetNameCodeField;
        
        private string streetNameField;
        
        private string streetNameEngField;
        
        private System.Nullable<int> basementField;
        
        private System.Nullable<int> buildingNumberMajorField;
        
        private System.Nullable<int> buildingNumberMinorField;
        
        private string buildingCodeField;
        
        private string buildingNameForBulkField;
        
        private string buildingNameField;
        
        private string registeredSuburbCodeField;
        
        private string registeredSuburbField;
        
        private string villageField;
        
        private System.Nullable<bool> sanField;
        
        private System.Nullable<int> lotNumberMajorField;
        
        private System.Nullable<int> lotNumberMinorField;
        
        /// <remarks/>
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        public string SequenceNumber {
            get {
                return this.sequenceNumberField;
            }
            set {
                this.sequenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProvinceEng {
            get {
                return this.provinceEngField;
            }
            set {
                this.provinceEngField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountyEng {
            get {
                return this.countyEngField;
            }
            set {
                this.countyEngField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Suburb {
            get {
                return this.suburbField;
            }
            set {
                this.suburbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SuburbEng {
            get {
                return this.suburbEngField;
            }
            set {
                this.suburbEngField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StreetNameCode {
            get {
                return this.streetNameCodeField;
            }
            set {
                this.streetNameCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StreetNameEng {
            get {
                return this.streetNameEngField;
            }
            set {
                this.streetNameEngField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Basement {
            get {
                return this.basementField;
            }
            set {
                this.basementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BuildingNumberMajor {
            get {
                return this.buildingNumberMajorField;
            }
            set {
                this.buildingNumberMajorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BuildingNumberMinor {
            get {
                return this.buildingNumberMinorField;
            }
            set {
                this.buildingNumberMinorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BuildingCode {
            get {
                return this.buildingCodeField;
            }
            set {
                this.buildingCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BuildingNameForBulk {
            get {
                return this.buildingNameForBulkField;
            }
            set {
                this.buildingNameForBulkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BuildingName {
            get {
                return this.buildingNameField;
            }
            set {
                this.buildingNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RegisteredSuburbCode {
            get {
                return this.registeredSuburbCodeField;
            }
            set {
                this.registeredSuburbCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RegisteredSuburb {
            get {
                return this.registeredSuburbField;
            }
            set {
                this.registeredSuburbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Village {
            get {
                return this.villageField;
            }
            set {
                this.villageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> San {
            get {
                return this.sanField;
            }
            set {
                this.sanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> LotNumberMajor {
            get {
                return this.lotNumberMajorField;
            }
            set {
                this.lotNumberMajorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> LotNumberMinor {
            get {
                return this.lotNumberMinorField;
            }
            set {
                this.lotNumberMinorField = value;
            }
        }
    }
}
