//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Aliencube.Utilities.KoreanPostcodeAddressUpdater.Services
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class KoreanPostcodeAddressDataContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new KoreanPostcodeAddressDataContext object using the connection string found in the 'KoreanPostcodeAddressDataContext' section of the application configuration file.
        /// </summary>
        public KoreanPostcodeAddressDataContext() : base("name=KoreanPostcodeAddressDataContext", "KoreanPostcodeAddressDataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KoreanPostcodeAddressDataContext object.
        /// </summary>
        public KoreanPostcodeAddressDataContext(string connectionString) : base(connectionString, "KoreanPostcodeAddressDataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KoreanPostcodeAddressDataContext object.
        /// </summary>
        public KoreanPostcodeAddressDataContext(EntityConnection connection) : base(connection, "KoreanPostcodeAddressDataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LotBasedAddress> LotBasedAddresses
        {
            get
            {
                if ((_LotBasedAddresses == null))
                {
                    _LotBasedAddresses = base.CreateObjectSet<LotBasedAddress>("LotBasedAddresses");
                }
                return _LotBasedAddresses;
            }
        }
        private ObjectSet<LotBasedAddress> _LotBasedAddresses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StreetBasedAddress> StreetBasedAddresses
        {
            get
            {
                if ((_StreetBasedAddresses == null))
                {
                    _StreetBasedAddresses = base.CreateObjectSet<StreetBasedAddress>("StreetBasedAddresses");
                }
                return _StreetBasedAddresses;
            }
        }
        private ObjectSet<StreetBasedAddress> _StreetBasedAddresses;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LotBasedAddresses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLotBasedAddresses(LotBasedAddress lotBasedAddress)
        {
            base.AddObject("LotBasedAddresses", lotBasedAddress);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StreetBasedAddresses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStreetBasedAddresses(StreetBasedAddress streetBasedAddress)
        {
            base.AddObject("StreetBasedAddresses", streetBasedAddress);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="addressType">No Metadata Documentation available.</param>
        public int DropCreateTables(global::System.String addressType)
        {
            ObjectParameter addressTypeParameter;
            if (addressType != null)
            {
                addressTypeParameter = new ObjectParameter("AddressType", addressType);
            }
            else
            {
                addressTypeParameter = new ObjectParameter("AddressType", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("DropCreateTables", addressTypeParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KoreanPostcodeAddressDataModel", Name="LotBasedAddress")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LotBasedAddress : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LotBasedAddress object.
        /// </summary>
        /// <param name="addressId">Initial value of the AddressId property.</param>
        /// <param name="postcode">Initial value of the Postcode property.</param>
        /// <param name="sequenceNumber">Initial value of the SequenceNumber property.</param>
        public static LotBasedAddress CreateLotBasedAddress(global::System.Int32 addressId, global::System.String postcode, global::System.Int32 sequenceNumber)
        {
            LotBasedAddress lotBasedAddress = new LotBasedAddress();
            lotBasedAddress.AddressId = addressId;
            lotBasedAddress.Postcode = postcode;
            lotBasedAddress.SequenceNumber = sequenceNumber;
            return lotBasedAddress;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AddressId
        {
            get
            {
                return _AddressId;
            }
            set
            {
                if (_AddressId != value)
                {
                    OnAddressIdChanging(value);
                    ReportPropertyChanging("AddressId");
                    _AddressId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AddressId");
                    OnAddressIdChanged();
                }
            }
        }
        private global::System.Int32 _AddressId;
        partial void OnAddressIdChanging(global::System.Int32 value);
        partial void OnAddressIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Postcode
        {
            get
            {
                return _Postcode;
            }
            set
            {
                OnPostcodeChanging(value);
                ReportPropertyChanging("Postcode");
                _Postcode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Postcode");
                OnPostcodeChanged();
            }
        }
        private global::System.String _Postcode;
        partial void OnPostcodeChanging(global::System.String value);
        partial void OnPostcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SequenceNumber
        {
            get
            {
                return _SequenceNumber;
            }
            set
            {
                OnSequenceNumberChanging(value);
                ReportPropertyChanging("SequenceNumber");
                _SequenceNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SequenceNumber");
                OnSequenceNumberChanged();
            }
        }
        private global::System.Int32 _SequenceNumber;
        partial void OnSequenceNumberChanging(global::System.Int32 value);
        partial void OnSequenceNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Province
        {
            get
            {
                return _Province;
            }
            set
            {
                OnProvinceChanging(value);
                ReportPropertyChanging("Province");
                _Province = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Province");
                OnProvinceChanged();
            }
        }
        private global::System.String _Province;
        partial void OnProvinceChanging(global::System.String value);
        partial void OnProvinceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String County
        {
            get
            {
                return _County;
            }
            set
            {
                OnCountyChanging(value);
                ReportPropertyChanging("County");
                _County = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("County");
                OnCountyChanged();
            }
        }
        private global::System.String _County;
        partial void OnCountyChanging(global::System.String value);
        partial void OnCountyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String District
        {
            get
            {
                return _District;
            }
            set
            {
                OnDistrictChanging(value);
                ReportPropertyChanging("District");
                _District = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("District");
                OnDistrictChanged();
            }
        }
        private global::System.String _District;
        partial void OnDistrictChanging(global::System.String value);
        partial void OnDistrictChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Suburb
        {
            get
            {
                return _Suburb;
            }
            set
            {
                OnSuburbChanging(value);
                ReportPropertyChanging("Suburb");
                _Suburb = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Suburb");
                OnSuburbChanged();
            }
        }
        private global::System.String _Suburb;
        partial void OnSuburbChanging(global::System.String value);
        partial void OnSuburbChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Village
        {
            get
            {
                return _Village;
            }
            set
            {
                OnVillageChanging(value);
                ReportPropertyChanging("Village");
                _Village = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Village");
                OnVillageChanged();
            }
        }
        private global::System.String _Village;
        partial void OnVillageChanging(global::System.String value);
        partial void OnVillageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Island
        {
            get
            {
                return _Island;
            }
            set
            {
                OnIslandChanging(value);
                ReportPropertyChanging("Island");
                _Island = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Island");
                OnIslandChanged();
            }
        }
        private global::System.String _Island;
        partial void OnIslandChanging(global::System.String value);
        partial void OnIslandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String San
        {
            get
            {
                return _San;
            }
            set
            {
                OnSanChanging(value);
                ReportPropertyChanging("San");
                _San = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("San");
                OnSanChanged();
            }
        }
        private global::System.String _San;
        partial void OnSanChanging(global::System.String value);
        partial void OnSanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LotNumberMajorFrom
        {
            get
            {
                return _LotNumberMajorFrom;
            }
            set
            {
                OnLotNumberMajorFromChanging(value);
                ReportPropertyChanging("LotNumberMajorFrom");
                _LotNumberMajorFrom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LotNumberMajorFrom");
                OnLotNumberMajorFromChanged();
            }
        }
        private Nullable<global::System.Int32> _LotNumberMajorFrom;
        partial void OnLotNumberMajorFromChanging(Nullable<global::System.Int32> value);
        partial void OnLotNumberMajorFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LotNumberMinorFrom
        {
            get
            {
                return _LotNumberMinorFrom;
            }
            set
            {
                OnLotNumberMinorFromChanging(value);
                ReportPropertyChanging("LotNumberMinorFrom");
                _LotNumberMinorFrom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LotNumberMinorFrom");
                OnLotNumberMinorFromChanged();
            }
        }
        private Nullable<global::System.Int32> _LotNumberMinorFrom;
        partial void OnLotNumberMinorFromChanging(Nullable<global::System.Int32> value);
        partial void OnLotNumberMinorFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LotNumberMajorTo
        {
            get
            {
                return _LotNumberMajorTo;
            }
            set
            {
                OnLotNumberMajorToChanging(value);
                ReportPropertyChanging("LotNumberMajorTo");
                _LotNumberMajorTo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LotNumberMajorTo");
                OnLotNumberMajorToChanged();
            }
        }
        private Nullable<global::System.Int32> _LotNumberMajorTo;
        partial void OnLotNumberMajorToChanging(Nullable<global::System.Int32> value);
        partial void OnLotNumberMajorToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LotNumberMinorTo
        {
            get
            {
                return _LotNumberMinorTo;
            }
            set
            {
                OnLotNumberMinorToChanging(value);
                ReportPropertyChanging("LotNumberMinorTo");
                _LotNumberMinorTo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LotNumberMinorTo");
                OnLotNumberMinorToChanged();
            }
        }
        private Nullable<global::System.Int32> _LotNumberMinorTo;
        partial void OnLotNumberMinorToChanging(Nullable<global::System.Int32> value);
        partial void OnLotNumberMinorToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BuildingName
        {
            get
            {
                return _BuildingName;
            }
            set
            {
                OnBuildingNameChanging(value);
                ReportPropertyChanging("BuildingName");
                _BuildingName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BuildingName");
                OnBuildingNameChanged();
            }
        }
        private global::System.String _BuildingName;
        partial void OnBuildingNameChanging(global::System.String value);
        partial void OnBuildingNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BuildingNumberFrom
        {
            get
            {
                return _BuildingNumberFrom;
            }
            set
            {
                OnBuildingNumberFromChanging(value);
                ReportPropertyChanging("BuildingNumberFrom");
                _BuildingNumberFrom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BuildingNumberFrom");
                OnBuildingNumberFromChanged();
            }
        }
        private Nullable<global::System.Int32> _BuildingNumberFrom;
        partial void OnBuildingNumberFromChanging(Nullable<global::System.Int32> value);
        partial void OnBuildingNumberFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BuildingNumberTo
        {
            get
            {
                return _BuildingNumberTo;
            }
            set
            {
                OnBuildingNumberToChanging(value);
                ReportPropertyChanging("BuildingNumberTo");
                _BuildingNumberTo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BuildingNumberTo");
                OnBuildingNumberToChanged();
            }
        }
        private Nullable<global::System.Int32> _BuildingNumberTo;
        partial void OnBuildingNumberToChanging(Nullable<global::System.Int32> value);
        partial void OnBuildingNumberToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateUpdated
        {
            get
            {
                return _DateUpdated;
            }
            set
            {
                OnDateUpdatedChanging(value);
                ReportPropertyChanging("DateUpdated");
                _DateUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateUpdated");
                OnDateUpdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateUpdated;
        partial void OnDateUpdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KoreanPostcodeAddressDataModel", Name="StreetBasedAddress")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StreetBasedAddress : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StreetBasedAddress object.
        /// </summary>
        /// <param name="addressId">Initial value of the AddressId property.</param>
        /// <param name="postcode">Initial value of the Postcode property.</param>
        /// <param name="sequenceNumber">Initial value of the SequenceNumber property.</param>
        public static StreetBasedAddress CreateStreetBasedAddress(global::System.Int32 addressId, global::System.String postcode, global::System.String sequenceNumber)
        {
            StreetBasedAddress streetBasedAddress = new StreetBasedAddress();
            streetBasedAddress.AddressId = addressId;
            streetBasedAddress.Postcode = postcode;
            streetBasedAddress.SequenceNumber = sequenceNumber;
            return streetBasedAddress;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AddressId
        {
            get
            {
                return _AddressId;
            }
            set
            {
                if (_AddressId != value)
                {
                    OnAddressIdChanging(value);
                    ReportPropertyChanging("AddressId");
                    _AddressId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AddressId");
                    OnAddressIdChanged();
                }
            }
        }
        private global::System.Int32 _AddressId;
        partial void OnAddressIdChanging(global::System.Int32 value);
        partial void OnAddressIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Postcode
        {
            get
            {
                return _Postcode;
            }
            set
            {
                OnPostcodeChanging(value);
                ReportPropertyChanging("Postcode");
                _Postcode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Postcode");
                OnPostcodeChanged();
            }
        }
        private global::System.String _Postcode;
        partial void OnPostcodeChanging(global::System.String value);
        partial void OnPostcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SequenceNumber
        {
            get
            {
                return _SequenceNumber;
            }
            set
            {
                OnSequenceNumberChanging(value);
                ReportPropertyChanging("SequenceNumber");
                _SequenceNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SequenceNumber");
                OnSequenceNumberChanged();
            }
        }
        private global::System.String _SequenceNumber;
        partial void OnSequenceNumberChanging(global::System.String value);
        partial void OnSequenceNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Province
        {
            get
            {
                return _Province;
            }
            set
            {
                OnProvinceChanging(value);
                ReportPropertyChanging("Province");
                _Province = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Province");
                OnProvinceChanged();
            }
        }
        private global::System.String _Province;
        partial void OnProvinceChanging(global::System.String value);
        partial void OnProvinceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProvinceEng
        {
            get
            {
                return _ProvinceEng;
            }
            set
            {
                OnProvinceEngChanging(value);
                ReportPropertyChanging("ProvinceEng");
                _ProvinceEng = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProvinceEng");
                OnProvinceEngChanged();
            }
        }
        private global::System.String _ProvinceEng;
        partial void OnProvinceEngChanging(global::System.String value);
        partial void OnProvinceEngChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CityEng
        {
            get
            {
                return _CityEng;
            }
            set
            {
                OnCityEngChanging(value);
                ReportPropertyChanging("CityEng");
                _CityEng = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CityEng");
                OnCityEngChanged();
            }
        }
        private global::System.String _CityEng;
        partial void OnCityEngChanging(global::System.String value);
        partial void OnCityEngChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String County
        {
            get
            {
                return _County;
            }
            set
            {
                OnCountyChanging(value);
                ReportPropertyChanging("County");
                _County = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("County");
                OnCountyChanged();
            }
        }
        private global::System.String _County;
        partial void OnCountyChanging(global::System.String value);
        partial void OnCountyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CountyEng
        {
            get
            {
                return _CountyEng;
            }
            set
            {
                OnCountyEngChanging(value);
                ReportPropertyChanging("CountyEng");
                _CountyEng = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CountyEng");
                OnCountyEngChanged();
            }
        }
        private global::System.String _CountyEng;
        partial void OnCountyEngChanging(global::System.String value);
        partial void OnCountyEngChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String District
        {
            get
            {
                return _District;
            }
            set
            {
                OnDistrictChanging(value);
                ReportPropertyChanging("District");
                _District = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("District");
                OnDistrictChanged();
            }
        }
        private global::System.String _District;
        partial void OnDistrictChanging(global::System.String value);
        partial void OnDistrictChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DistrictEng
        {
            get
            {
                return _DistrictEng;
            }
            set
            {
                OnDistrictEngChanging(value);
                ReportPropertyChanging("DistrictEng");
                _DistrictEng = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DistrictEng");
                OnDistrictEngChanged();
            }
        }
        private global::System.String _DistrictEng;
        partial void OnDistrictEngChanging(global::System.String value);
        partial void OnDistrictEngChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Suburb
        {
            get
            {
                return _Suburb;
            }
            set
            {
                OnSuburbChanging(value);
                ReportPropertyChanging("Suburb");
                _Suburb = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Suburb");
                OnSuburbChanged();
            }
        }
        private global::System.String _Suburb;
        partial void OnSuburbChanging(global::System.String value);
        partial void OnSuburbChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SuburbEng
        {
            get
            {
                return _SuburbEng;
            }
            set
            {
                OnSuburbEngChanging(value);
                ReportPropertyChanging("SuburbEng");
                _SuburbEng = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SuburbEng");
                OnSuburbEngChanged();
            }
        }
        private global::System.String _SuburbEng;
        partial void OnSuburbEngChanging(global::System.String value);
        partial void OnSuburbEngChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StreetNameCode
        {
            get
            {
                return _StreetNameCode;
            }
            set
            {
                OnStreetNameCodeChanging(value);
                ReportPropertyChanging("StreetNameCode");
                _StreetNameCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StreetNameCode");
                OnStreetNameCodeChanged();
            }
        }
        private global::System.String _StreetNameCode;
        partial void OnStreetNameCodeChanging(global::System.String value);
        partial void OnStreetNameCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StreetName
        {
            get
            {
                return _StreetName;
            }
            set
            {
                OnStreetNameChanging(value);
                ReportPropertyChanging("StreetName");
                _StreetName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StreetName");
                OnStreetNameChanged();
            }
        }
        private global::System.String _StreetName;
        partial void OnStreetNameChanging(global::System.String value);
        partial void OnStreetNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StreetNameEng
        {
            get
            {
                return _StreetNameEng;
            }
            set
            {
                OnStreetNameEngChanging(value);
                ReportPropertyChanging("StreetNameEng");
                _StreetNameEng = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StreetNameEng");
                OnStreetNameEngChanged();
            }
        }
        private global::System.String _StreetNameEng;
        partial void OnStreetNameEngChanging(global::System.String value);
        partial void OnStreetNameEngChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Basement
        {
            get
            {
                return _Basement;
            }
            set
            {
                OnBasementChanging(value);
                ReportPropertyChanging("Basement");
                _Basement = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Basement");
                OnBasementChanged();
            }
        }
        private Nullable<global::System.Int32> _Basement;
        partial void OnBasementChanging(Nullable<global::System.Int32> value);
        partial void OnBasementChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BuildingNumberMajor
        {
            get
            {
                return _BuildingNumberMajor;
            }
            set
            {
                OnBuildingNumberMajorChanging(value);
                ReportPropertyChanging("BuildingNumberMajor");
                _BuildingNumberMajor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BuildingNumberMajor");
                OnBuildingNumberMajorChanged();
            }
        }
        private Nullable<global::System.Int32> _BuildingNumberMajor;
        partial void OnBuildingNumberMajorChanging(Nullable<global::System.Int32> value);
        partial void OnBuildingNumberMajorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BuildingNumberMinor
        {
            get
            {
                return _BuildingNumberMinor;
            }
            set
            {
                OnBuildingNumberMinorChanging(value);
                ReportPropertyChanging("BuildingNumberMinor");
                _BuildingNumberMinor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BuildingNumberMinor");
                OnBuildingNumberMinorChanged();
            }
        }
        private Nullable<global::System.Int32> _BuildingNumberMinor;
        partial void OnBuildingNumberMinorChanging(Nullable<global::System.Int32> value);
        partial void OnBuildingNumberMinorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BuildingCode
        {
            get
            {
                return _BuildingCode;
            }
            set
            {
                OnBuildingCodeChanging(value);
                ReportPropertyChanging("BuildingCode");
                _BuildingCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BuildingCode");
                OnBuildingCodeChanged();
            }
        }
        private global::System.String _BuildingCode;
        partial void OnBuildingCodeChanging(global::System.String value);
        partial void OnBuildingCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BuildingNameForBulk
        {
            get
            {
                return _BuildingNameForBulk;
            }
            set
            {
                OnBuildingNameForBulkChanging(value);
                ReportPropertyChanging("BuildingNameForBulk");
                _BuildingNameForBulk = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BuildingNameForBulk");
                OnBuildingNameForBulkChanged();
            }
        }
        private global::System.String _BuildingNameForBulk;
        partial void OnBuildingNameForBulkChanging(global::System.String value);
        partial void OnBuildingNameForBulkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BuildingName
        {
            get
            {
                return _BuildingName;
            }
            set
            {
                OnBuildingNameChanging(value);
                ReportPropertyChanging("BuildingName");
                _BuildingName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BuildingName");
                OnBuildingNameChanged();
            }
        }
        private global::System.String _BuildingName;
        partial void OnBuildingNameChanging(global::System.String value);
        partial void OnBuildingNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegisteredSuburbCode
        {
            get
            {
                return _RegisteredSuburbCode;
            }
            set
            {
                OnRegisteredSuburbCodeChanging(value);
                ReportPropertyChanging("RegisteredSuburbCode");
                _RegisteredSuburbCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RegisteredSuburbCode");
                OnRegisteredSuburbCodeChanged();
            }
        }
        private global::System.String _RegisteredSuburbCode;
        partial void OnRegisteredSuburbCodeChanging(global::System.String value);
        partial void OnRegisteredSuburbCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegisteredSuburb
        {
            get
            {
                return _RegisteredSuburb;
            }
            set
            {
                OnRegisteredSuburbChanging(value);
                ReportPropertyChanging("RegisteredSuburb");
                _RegisteredSuburb = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RegisteredSuburb");
                OnRegisteredSuburbChanged();
            }
        }
        private global::System.String _RegisteredSuburb;
        partial void OnRegisteredSuburbChanging(global::System.String value);
        partial void OnRegisteredSuburbChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SuburbSequenceNumber
        {
            get
            {
                return _SuburbSequenceNumber;
            }
            set
            {
                OnSuburbSequenceNumberChanging(value);
                ReportPropertyChanging("SuburbSequenceNumber");
                _SuburbSequenceNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SuburbSequenceNumber");
                OnSuburbSequenceNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _SuburbSequenceNumber;
        partial void OnSuburbSequenceNumberChanging(Nullable<global::System.Int32> value);
        partial void OnSuburbSequenceNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Village
        {
            get
            {
                return _Village;
            }
            set
            {
                OnVillageChanging(value);
                ReportPropertyChanging("Village");
                _Village = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Village");
                OnVillageChanged();
            }
        }
        private global::System.String _Village;
        partial void OnVillageChanging(global::System.String value);
        partial void OnVillageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> San
        {
            get
            {
                return _San;
            }
            set
            {
                OnSanChanging(value);
                ReportPropertyChanging("San");
                _San = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("San");
                OnSanChanged();
            }
        }
        private Nullable<global::System.Boolean> _San;
        partial void OnSanChanging(Nullable<global::System.Boolean> value);
        partial void OnSanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LotNumberMajor
        {
            get
            {
                return _LotNumberMajor;
            }
            set
            {
                OnLotNumberMajorChanging(value);
                ReportPropertyChanging("LotNumberMajor");
                _LotNumberMajor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LotNumberMajor");
                OnLotNumberMajorChanged();
            }
        }
        private Nullable<global::System.Int32> _LotNumberMajor;
        partial void OnLotNumberMajorChanging(Nullable<global::System.Int32> value);
        partial void OnLotNumberMajorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LotNumberMinor
        {
            get
            {
                return _LotNumberMinor;
            }
            set
            {
                OnLotNumberMinorChanging(value);
                ReportPropertyChanging("LotNumberMinor");
                _LotNumberMinor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LotNumberMinor");
                OnLotNumberMinorChanged();
            }
        }
        private Nullable<global::System.Int32> _LotNumberMinor;
        partial void OnLotNumberMinorChanging(Nullable<global::System.Int32> value);
        partial void OnLotNumberMinorChanged();

        #endregion

    
    }

    #endregion

    
}
